<?php

namespace Tests\Features;

use Tests\TestCase;

use App\Models\User;
use App\Http\Controllers\UserController;

class RegistrationTest extends TestCase
{


    private const USER_CREATE_ENDPOINT = 'api/user';


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        User::where('email', 'johnfoo@bar.com')->get()->delete();
    }


    /**
     * Test a basic user create
     */
    public function test_userCreate()
    {
        $postData = [
            'name' => 'John Foo',
            'email' => 'johnfoo@bar.com',
            'password' => 'somesillypassword',
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);
        $response->assertStatus(200);
        $response->assertSuccessful();
        $response->assertExactJson([
            'success' => UserController::USER_CREATED_SUCCESS_MSG,
        ]);

        $user = User::where('email', 'johnfoo@bar.com')->first();


        $this->assertArrayHasKey('name', $user);
        $this->assertSame($user['name'], 'John Foo');
    }


    public function test_userCreateNoNameError(): void
    {
        $postData = [
            'name' => '',
            'email' => 'johnfoo@bar.com',
            'password' => 'somesillypassword'
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::MISSING_NAME_ERR_MSG,
        ]);
    }


    public function testUserCreateInvalidNameError(): void
    {
        $postData = [
            'name' => '!nv@l!d\us3rnam3!',
            'email' => 'johnfoo@bar.com',
            'password' => 'somesillypassword'
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::INVALID_NAME_ERR_MSG,
        ]);
    }

    public function testUserCreateNoEmailError(): void
    {
        $postData = [
            'name' => 'John Foo',
            'email' => '',
            'password' => 'somesillypassword'
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::MISSING_EMAIL_ERR_MSG,
        ]);
    }

    public function testUserCreateInvalidEmailError(): void
    {
        $postData = [
            'name' => 'John Foo',
            'email' => 'someemail',
            'password' => 'somesillypassword'
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::INVALID_EMAIL_ERR_MSG,
        ]);
    }

    public function testUserCreateNoPasswordError(): void
    {
        $postData = [
            'name' => 'John Foo',
            'email' => 'johnfoo@bar.com',
            'password' => ''
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::MISSING_PASSWORD_ERR_MSG,
        ]);
    }

    public function testUserCreateInvalidPasswordError(): void
    {
        $postData = [
            'name' => 'John Foo',
            'email' => 'johnfoo@bar.com',
            'password' => 'tooshort'
        ];

        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::INVALID_PASSWORD_ERR_MSG,
        ]);
    }

    public function testUserCreateEmailAlreadyInUser(): void
    {
        $postData = [
            'name' => 'John Foo',
            'email' => 'johnfoo@bar.com',
            'password' => 'somesillypassword'
        ];

        // Make sure the resource exists
        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);
        $response->assertStatus(200);
        $response->assertSuccessful();


        $user = User::where('name', 'John Foo')->first();
        $this->assertArrayHasKey('name', $user);
        $this->assertSame($user['name'], 'John Foo');


        // Make the request again, this time it should be a duplicate resource.
        $response = $this->post(self::USER_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'error' => UserController::EMAIL_EXISTS_ERR_MSG,
        ]);
    }


}
