<?php

namespace Tests\Features;

use App\Http\Controllers\UserInterestController;
use App\Models\Activity;
use App\Models\Attitude;
use App\Models\SkillLevel;
use Tests\TestCase;

use App\Models\User;
use App\Http\Controllers\UserController;

class RegistrationTest extends TestCase
{


    private const USER_INTEREST_CREATE_ENDPOINT = 'api/user/interest';


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        User::query()->delete();


        Activity::query()->delete();
        Attitude::query()->delete();
        SkillLevel::query()->delete();

        $this->createActivities();
        $this->createAttitudes();
        $this->createSkillLevels();
    }


    private function createActivities(): void
    {
        foreach(Activity::PRESET_VALUES as $value)
        {
            Activity::create(['name' => $value]);
        }
    }

    private function createAttitudes(): void
    {
        foreach(Attitude::PRESET_VALUES as $value)
        {
            Attitude::create(['name' => $value]);
        }
    }

    private function createSkillLevels(): void
    {
        foreach(SkillLevel::PRESET_VALUES as $value)
        {
            SkillLevel::create(['name' => $value]);
        }
    }


    public function createSingleUserInterestTest(): void
    {
        $postData = [
          'activity' => 'Hiking',
          'attitude' => 'Interested',
          'skillLevel' => 'Skilled',
        ];

        $response = $this->post(self::USER_INTEREST_CREATE_ENDPOINT, $postData);

        $response->assertStatus(200);
        $response->assertExactJson([
            'success' => UserInterestController::INTEREST_ADDED,
        ]);



    }




}
